# -*- coding: utf-8 -*-

if __name__ == '__main__':

	with open('bd') as f:
		bd = f.readlines()

	with open('estados') as f:
		estados = f.readlines()

	with open('linhas') as f:
		linhas = f.readlines()

	for i in range(0,len(estados)):
		estado = estados[i]
		linha = linhas[i].split(' ')
		f = open('/home/felipe/Documents/UFBA/MATC82/PostoBarato/src/postobarato/database/estatisticas/'+str(estado).replace('\n', ''), 'w')
		f.write('{\n')
		f.write('\t"resumos":[\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Maio 2016",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[0])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[1])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[2])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t},\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Abril 2016",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[3])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[4])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[5])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t},\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Março 2016",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[6])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[7])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[8])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t},\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Fevereiro 2016",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[9])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[10])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[11])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t},\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Janeiro 2016",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[12])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[13])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[14])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t},\n')

		f.write('\t\t{\n')
		f.write('\t\t\t"periodo":"Dezembro 2015",\n')
		f.write('\t\t\t"produtos":[\n')

		tempi = int(linha[15])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Gasolina",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[16])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Álcool",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t},\n')

		tempi = int(linha[17])
		temp = bd[tempi-1].split(' ')
		f.write('\t\t\t\t{\n')
		f.write('\t\t\t\t\t"nome":"Diesel",\n')
		f.write('\t\t\t\t\t"numero_postos":'+temp[0]+',\n')
		f.write('\t\t\t\t\t"preco_medio":'+temp[1]+',\n')
		f.write('\t\t\t\t\t"desvio_padrao":'+temp[2]+',\n')
		f.write('\t\t\t\t\t"preco_minimo":'+temp[3]+',\n')
		f.write('\t\t\t\t\t"preco_maximo":'+temp[4])
		f.write('\t\t\t\t}\n')

		f.write('\t\t\t]\n')
		f.write('\t\t}\n')

		f.write('\t]\n')
		f.write('}')
		f.close()
